### ISSUE TITLE
Set sidebar as closed as default on all pages

### ISSUE THREAD

**Issue by pmgeuze** [turnermm/simple_sidebar#1]
Please let me know if there is a way that I can set the code to have the sidebar:user closed on all pages.

I use the side bar to have access to all pages or options, when I need them, but for most pages, I will not need the sidebar. I usually use the Folding plugin, but I appreciate having the sidebar compress to give me more screen space most of the time.

Thank you.

**Comment by turnermm** [comment]
This is an old template, and while it still works,  it may not have access to recent features.  However, there is a toggle above the sidebar
<img width="112" alt="sstoggle" src="https://user-images.githubusercontent.com/176447/155893582-383ccf2b-ff21-4bb8-9c48-e876d58460a9.png">

Clicking on the double arrow will open and close the sidebar.

**Comment by pmgeuze** [comment]
Sir,

Thank you for both your quick response and the great template.

I appreciate your long time support and work with Dokuwiki.

Pieter-Michiel

**Comment by turnermm** [comment]
Just as a matter of interest,  my template is based on the old default DokuWiki template,which the current one replaced.
